#Site
title: DrCBin-陈斌
description: 陈斌的个人博客
logo: favicon.png
url: http://drcbin.com
rss_url: /feed.xml

# Jekyll
permalink:          /blog/:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
sass:
  sass_dir:         assets/_sass
  style:            compressed

# Comment
comment:
  # disqus: ChenBin...
  # duoshuo: kongsong
  # youyan: 2122392
  # laibili: MTAyMC8yODgzNC81NDA0

# Website analytics
google_analytics: UA-110406741-1
baidu_analytics: cd1138e3c986773ec07b6dd699f7bec2    #from //hm.baidu.com/hm.js?***

# Author information:
author:
  #resume: /resume
  name: ChenBin     #the name of Blog section
  about_me: "记录生活,记录点滴！这是本人博客!
    我叫陈斌,19届Computer&Science本科生, 目前在研究和学习区块链技术,数据分析以及量化交易, 未来希望从事金融和投资领域的开发! 计算机是真爱,但不想把计算机当做饭碗,希望能直接和钱打交道!
    马上要实习了, 希望能找个金融领域相关的公司实习,希望是上规模的大公司,或者初创的公司! 最好是区块链实习! 有推荐的同学希望帮忙推荐下!Qq:2720043432"
 
# Social Links
email:               drcbin@google.com
#google.plus:        username
#twitter:            username
# facebook:            username
github:             DrCBin
# stackoverflow:      6438519/song-kong   #from a "http://stackoverflow.com/users/123456/username" link
# linkedin:           kongsong
#xing:              username
#instagram:          username
#lastfm:            username
#tumblr:            username
#pinterest:         username
#foursquare:        username
#steam:              username
#dribbble:          username
#youtube:           username
#soundcloud:        username
#weibo:             username
#flickr:            username
#codepen:           username
#keybase:           username
#xmpp:              username@server.com
#hackernews:        username
#behance:           username

# Gems
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, _site, src, vendor, CNAME, LICENSE, Rakefile,.sass-cache,.DS_Store,.idea]
